
import com.sun.org.apache.bcel.internal.classfile.Utility;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Harga3 = new javax.swing.JTextField();
        Diskon = new javax.swing.JTextField();
        Proses = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        Harga1 = new javax.swing.JTextField();
        Harga2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("PEMBAYARAN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 0, 160, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Barang 1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 60, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Barang 2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 110, 100, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Barang 3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 60, 100, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Diskon");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 110, 100, 40);

        Harga3.setBackground(new java.awt.Color(255, 204, 204));
        Harga3.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(Harga3);
        Harga3.setBounds(490, 60, 190, 30);

        Diskon.setBackground(new java.awt.Color(255, 204, 204));
        Diskon.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(Diskon);
        Diskon.setBounds(490, 110, 190, 30);

        Proses.setBackground(new java.awt.Color(204, 204, 255));
        Proses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Proses.setForeground(new java.awt.Color(204, 0, 0));
        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        jPanel1.add(Proses);
        Proses.setBounds(180, 150, 110, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Total Bayar");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 200, 120, 30);

        Hasil.setBackground(new java.awt.Color(255, 204, 204));
        Hasil.setColumns(20);
        Hasil.setForeground(new java.awt.Color(0, 51, 51));
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 200, 310, 130);

        Harga1.setBackground(new java.awt.Color(255, 204, 204));
        Harga1.setForeground(new java.awt.Color(0, 51, 51));
        Harga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Harga1ActionPerformed(evt);
            }
        });
        jPanel1.add(Harga1);
        Harga1.setBounds(150, 60, 190, 30);

        Harga2.setBackground(new java.awt.Color(255, 204, 204));
        Harga2.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(Harga2);
        Harga2.setBounds(150, 110, 190, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Harga");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 30, 80, 30);

        Keluar.setBackground(new java.awt.Color(204, 204, 255));
        Keluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Keluar.setForeground(new java.awt.Color(204, 0, 0));
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel1.add(Keluar);
        Keluar.setBounds(500, 150, 110, 40);

        Hapus.setBackground(new java.awt.Color(204, 204, 255));
        Hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Hapus.setForeground(new java.awt.Color(204, 0, 0));
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus);
        Hapus.setBounds(340, 150, 110, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 350);

        setBounds(0, 0, 729, 386);
    }// </editor-fold>//GEN-END:initComponents

    private void Harga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Harga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Harga1ActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        int barang1 = Integer.parseInt(Harga1.getText());
        int barang2 = Integer.parseInt(Harga2.getText());
        int barang3 = Integer.parseInt(Harga3.getText());
        int diskon  = Integer.parseInt(Diskon.getText());

        int hasiltotal = barang1+barang2+barang3;
        int totaldiskon = hasiltotal * diskon/100;
        int totalbayar = hasiltotal-totaldiskon;
        
        Hasil.setText("Harga barang 1 : "+barang1+
            "\nHarga barang 2 : "+ barang2+
            "\nHarga barang 3 : "+ barang3+
            "\nTotal Harga : "+hasiltotal+
            "\nDiskon : "+diskon+"%     /   Rp "+totaldiskon+
            "\nTotal Bayar : "+ totalbayar);

    }//GEN-LAST:event_ProsesActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
       Hasil.setText("");
       Harga1.setText("");
       Harga2.setText("");
       Harga3.setText("");
       Diskon.setText("");
       
// TODO add your handling code here:
    }//GEN-LAST:event_HapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Harga1;
    private javax.swing.JTextField Harga2;
    private javax.swing.JTextField Harga3;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Proses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
